<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.service.discovery</groupId>
    <artifactId>service_discovery</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>service-registry</module>
        <module>contracts</module>
        <module>service-discovery-loadbalancer-sidecar</module>
    </modules>

    <properties>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencyManagement>
        <dependencies>
            <!-- Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>5.14.2</version>
                <scope>test</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.mockito/mockito-core -->
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.14.2</version>
                <scope>test</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter -->
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>5.14.2</version>
                <scope>test</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.fasterxml.uuid/java-uuid-generator -->
            <dependency>
                <groupId>com.fasterxml.uuid</groupId>
                <artifactId>java-uuid-generator</artifactId>
                <version>5.2.0</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/io.etcd/jetcd-core -->
            <dependency>
                <groupId>io.etcd</groupId>
                <artifactId>jetcd-core</artifactId>
                <version>0.8.6</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/com.dslplatform/dsl-json -->
            <dependency>
                <groupId>com.dslplatform</groupId>
                <artifactId>dsl-json</artifactId>
                <version>2.0.2</version>
                <scope>compile</scope>
            </dependency>

            <!-- Source: https://mvnrepository.com/artifact/org.testcontainers/testcontainers -->
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>2.0.3</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>1.21.4</version>
                <scope>test</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>