spring.application.name=ServiceRegistryExample

spring.docker.compose.enabled=false

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/users_db
spring.datasource.username=myuser
spring.datasource.password=secret

etcd.endpoint=http://etcd:2379
service.name=user-service