spring.application.name=ServiceRegistryExample
spring.docker.compose.enabled=true
spring.docker.compose.file=service-registry-example/compose.yaml

spring.datasource.url=jdbc:postgresql://localhost:5431/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

etcd.endpoint=http://localhost:2379
service.name=user-service